/**
 * @file    main.cpp
 * @brief   UART → ESP-NOW Bridge using user_app custom messages
 *
 * This node acts as a transparent relay:
 *   1. Receives SensorReading events from a sensor node via UART.
 *   2. Retransmits every received SensorReading to all ESP-NOW peers.
 *   3. Handles SetMotor requests received via UART and replies locally.
 *
 * Message types are defined with the SerialComm IDL (user_app/) and
 * their C++ structs + serialisers are auto-generated by generate.py.
 *
 * ── Transport layout ─────────────────────────────────────────────────
 *
 *   [ Sensor Node ] ──UART──▶ [ Bridge (this) ] ──ESP-NOW──▶ [ Remote nodes ]
 *
 *   Slot 0 : UART      rx=true   tx=false   (wire: only receive)
 *   Slot 1 : ESP-NOW   rx=false  tx=true    (wireless: only transmit)
 *
 * ── ESP-NOW peer registration ─────────────────────────────────────────
 *
 *   There are two modes — choose one by setting USE_BROADCAST below:
 *
 *   Broadcast (simplest — no add_peer() call needed):
 *     • HardwareConfig.tx_peer_mac defaults to {0xFF,...}.
 *     • ESPNowTransport::init() auto-registers this broadcast address.
 *     • Every ESP-NOW device in range receives the frame.
 *
 *   Unicast (send to one specific node):
 *     • Set TARGET_MAC to the destination device's MAC address.
 *     • Call espnow_transport.add_peer(TARGET_MAC) once after init().
 *       add_peer() calls esp_now_add_peer() internally and records the
 *       peer in the transport's registry for future V2 routing.
 *     • Optionally call espnow_transport.set_tx_peer(TARGET_MAC) if you
 *       want to change the default TX destination at runtime without
 *       reconstructing the transport.
 *
 * ── How to get the peer MAC ──────────────────────────────────────────
 *
 *   Flash espnow_example on the target device; it prints its MAC on
 *   boot:  "MAC: AA:BB:CC:DD:EE:FF"
 *   Copy those bytes into TARGET_MAC below.
 *
 * ── Hardware connections ─────────────────────────────────────────────
 *
 *   Bridge GPIO 17  (TX2) ──▶  Sensor Node RX
 *   Bridge GPIO 16  (RX2) ◀──  Sensor Node TX
 *   GND ◀──────────────────────────────────── GND
 *
 *   ESP-NOW uses the onboard Wi-Fi antenna; no extra wiring needed.
 *
 * ── Generated types used ─────────────────────────────────────────────
 *
 *   SensorReading          (event)   ← user_app/event/SensorReading.event
 *   SetMotor_Request       (request) ← user_app/request/SetMotor.request
 *   SetMotor_Response      (request) ← user_app/request/SetMotor.request
 *   GpsCoord               (struct)  ← user_app/struct/GpsCoord.struct
 *
 *   Regenerate with:
 *     python user_app/generate.py \
 *         --input  user_app \
 *         --output include/serial_comm/generated
 */

/* ── Peer mode ────────────────────────────────────────────────────────
 * Define USE_BROADCAST for the simplest setup (no add_peer() needed).
 * Comment it out and fill in TARGET_MAC for unicast delivery.          */
#define USE_BROADCAST

#ifndef USE_BROADCAST
/* Replace with the target device's actual MAC address */
static const uint8_t TARGET_MAC[6] = {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF};
#endif

/* ── Includes ──────────────────────────────────────────────────────── */
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "esp_log.h"
#include "esp_err.h"
#include "nvs_flash.h"
#include "esp_wifi.h"
#include "esp_netif.h"
#include "esp_mac.h"

#include "serial_comm/transport/uart_serial_comm.h"
#include "serial_comm/transport/espnow_serial_comm.h"
#include "serial_comm/transport/multi_transport.h"
#include "serial_comm/serial_comm.h"
#include "serial_comm/middleware/serial_comm_manager.h"
#include "serial_comm/middleware/service/serial_comm_service.h"
#include "serial_comm/middleware/topic/serial_comm_topic.h"

/* Generated types and their serialisers */
#include "serial_comm/generated/generated_serializers.hpp"
#include "serial_comm/generated/event/sensor_reading.hpp"
#include "serial_comm/generated/request/set_motor.hpp"

static const char* TAG = "BRIDGE";

/* ── Command IDs ───────────────────────────────────────────────────── */
/* These must match what the sensor node uses when publishing/calling. */
static constexpr SerialCommCommand SENSOR_CMD = SerialCommCommand::STATUS_TOPIC;
static constexpr SerialCommCommand MOTOR_CMD  = SerialCommCommand::WRITE;

/* ── Relay queue (UART RX → ESP-NOW TX) ─────────────────────────────
 * The subscription callback runs inside the SerialComm RX task.
 * Re-publishing from that same task context is valid but blocks the
 * pipeline while ESP-NOW sends each fragment.  A dedicated relay task
 * keeps the RX pipeline free.                                          */
static QueueHandle_t relay_queue = nullptr;

/* Global manager pointer for the relay task */
static SerialCommManager* g_mgr = nullptr;

/* ── Callbacks ─────────────────────────────────────────────────────── */

static void on_sensor_reading(const SensorReading& msg) {
    /* Enqueue for relay — never block: drop if full */
    if (xQueueSend(relay_queue, &msg, 0) != pdTRUE) {
        ESP_LOGW(TAG, "[UART RX] Relay queue full — SensorReading dropped");
    } else {
        ESP_LOGD(TAG, "[UART RX] SensorReading queued for ESP-NOW relay "
                      "(T=%.1f H=%.1f ts=%lu ms)",
                 msg.temperature, msg.humidity,
                 (unsigned long)msg.timestamp_ms);
    }
}

static bool on_set_motor(const SetMotor_Request& req, SetMotor_Response& res) {
    ESP_LOGI(TAG, "[UART RX] SetMotor  motor=%u  speed=%.2f  enable=%s",
             req.motor_id, req.speed, req.enable ? "yes" : "no");

    /* Execute locally — drive the motor, read encoder, etc. */
    res.success      = true;
    res.actual_speed = req.speed;  /* echo back the requested speed */

    ESP_LOGI(TAG, "[UART TX] SetMotor response sent  actual_speed=%.2f",
             res.actual_speed);
    return true;
}

/* ── Relay task ────────────────────────────────────────────────────── */

static void relay_task_fn(void* /*arg*/) {
    SensorReading msg;

    while (true) {
        if (xQueueReceive(relay_queue, &msg, portMAX_DELAY) != pdTRUE) {
            continue;
        }

        /* Re-publish via the same manager — write() goes to ESP-NOW only
         * because MultiTransport's UART slot has tx_enabled=false.      */
        errCode err = g_mgr->publish<SensorReading>(SENSOR_CMD, msg);

        if (err == errCode::OK) {
            ESP_LOGI(TAG, "[ESP-NOW TX] SensorReading relayed "
                          "(T=%.1f  H=%.1f  ts=%lu ms  lat=%.4f lon=%.4f)",
                     msg.temperature, msg.humidity,
                     (unsigned long)msg.timestamp_ms,
                     msg.location.latitude, msg.location.longitude);
        } else {
            ESP_LOGW(TAG, "[ESP-NOW TX] Relay failed: %s", err_to_str(err));
        }
    }
}

/* ── WiFi init (required before ESPNowTransport::init()) ───────────── */

static void wifi_init_for_espnow(void) {
    ESP_ERROR_CHECK(nvs_flash_init());
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    wifi_init_config_t wcfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&wcfg));
    ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_RAM));
    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK(esp_wifi_start());
    ESP_ERROR_CHECK(esp_wifi_set_ps(WIFI_PS_NONE));

    uint8_t mac[6];
    esp_wifi_get_mac(WIFI_IF_STA, mac);
    ESP_LOGI(TAG, "Bridge MAC: %02X:%02X:%02X:%02X:%02X:%02X",
             mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
}

/* ── app_main ──────────────────────────────────────────────────────── */

extern "C" void app_main(void) {

    ESP_LOGI(TAG, "=== UART → ESP-NOW Bridge (user_app types) ===");

    /* ── WiFi ─────────────────────────────────────────────────────── */
    wifi_init_for_espnow();

    /* ── Relay queue ──────────────────────────────────────────────── */
    relay_queue = xQueueCreate(8, sizeof(SensorReading));
    if (!relay_queue) {
        ESP_LOGE(TAG, "Failed to create relay queue");
        return;
    }

    /* ── UART transport (RX only) ─────────────────────────────────── */
    UARTTransport::HardwareConfig uart_hw{};
    uart_hw.uart_port = UART_NUM_2;
    uart_hw.tx_pin    = 17;
    uart_hw.rx_pin    = 16;

    static UARTTransport uart(uart_hw);

    if (uart.init() != errCode::OK) {
        ESP_LOGE(TAG, "UART init failed"); return;
    }
    if (uart.start() != errCode::OK) {
        ESP_LOGE(TAG, "UART start failed"); return;
    }
    ESP_LOGI(TAG, "UART ready (UART%d  RX=GPIO%d  TX=GPIO%d)",
             (int)uart_hw.uart_port, uart_hw.rx_pin, uart_hw.tx_pin);

    /* ── ESP-NOW transport (TX only) ──────────────────────────────── */
    ESPNowTransport::HardwareConfig espnow_hw{};

#ifdef USE_BROADCAST
    /* Broadcast: tx_peer_mac already defaults to {0xFF,...}.
     * init() registers it automatically — no add_peer() needed.      */
    ESP_LOGI(TAG, "ESP-NOW mode: BROADCAST (all devices in range)");
#else
    /* Unicast: target a specific device by MAC address.
     * Step 1 — tell the transport what MAC to send to by default.    */
    memcpy(espnow_hw.tx_peer_mac, TARGET_MAC, 6);
    ESP_LOGI(TAG, "ESP-NOW mode: UNICAST → %02X:%02X:%02X:%02X:%02X:%02X",
             TARGET_MAC[0], TARGET_MAC[1], TARGET_MAC[2],
             TARGET_MAC[3], TARGET_MAC[4], TARGET_MAC[5]);
#endif

    static ESPNowTransport espnow(espnow_hw);

    if (espnow.init() != errCode::OK) {
        ESP_LOGE(TAG, "ESP-NOW init failed"); return;
    }

#ifndef USE_BROADCAST
    /* Unicast step 2 — register the peer with the ESP-NOW driver.
     *
     *   add_peer(mac, node_id, channel, encrypt, lmk)
     *
     *   • mac      : 6-byte destination address
     *   • node_id  : logical ID for V2 routing (0xFF = wildcard / unset)
     *   • channel  : Wi-Fi channel (0 = follow current channel)
     *   • encrypt  : enable link-layer encryption (requires PMK set in hw config)
     *   • lmk      : local master key for this peer (only when encrypt=true)
     *
     *   init() already registered tx_peer_mac as the default peer above,
     *   so this call would normally be redundant for the default peer.
     *   Use add_peer() when you want to register EXTRA unicast destinations
     *   in addition to the default (e.g. a second receiver node).         */
    if (espnow.add_peer(TARGET_MAC) != errCode::OK) {
        ESP_LOGW(TAG, "add_peer() failed — check that the MAC is correct");
    }
#endif

    if (espnow.start() != errCode::OK) {
        ESP_LOGE(TAG, "ESP-NOW start failed"); return;
    }
    ESP_LOGI(TAG, "ESP-NOW transport ready");

    /* ── MultiTransport: UART(rx) + ESP-NOW(tx) ──────────────────── */
    static MultiTransport multi;

    MultiTransport::SlotConfig uart_slot{};
    uart_slot.rx_enabled = true;
    uart_slot.tx_enabled = false;   /* bridge never sends back via UART */

    MultiTransport::SlotConfig espnow_slot{};
    espnow_slot.rx_enabled = false; /* bridge never receives via ESP-NOW */
    espnow_slot.tx_enabled = true;

    multi.add_transport(&uart,   uart_slot);
    multi.add_transport(&espnow, espnow_slot);

    if (multi.init() != errCode::OK) {
        ESP_LOGE(TAG, "MultiTransport init failed"); return;
    }
    if (multi.start() != errCode::OK) {
        ESP_LOGE(TAG, "MultiTransport start failed"); return;
    }

    /* ── SerialComm ───────────────────────────────────────────────── */
    static SerialComm comm(&multi);

    if (comm.init() != errCode::OK) {
        ESP_LOGE(TAG, "SerialComm init failed"); return;
    }
    if (comm.start() != errCode::OK) {
        ESP_LOGE(TAG, "SerialComm start failed"); return;
    }

    /* ── SerialCommManager ────────────────────────────────────────── */
    static SerialCommManager mgr(&comm);
    g_mgr = &mgr;

    if (mgr.init() != errCode::OK) {
        ESP_LOGE(TAG, "SerialCommManager init failed"); return;
    }

    /* Subscribe to SensorReading events (arrives via UART) */
    static SerialCommTopic<SensorReading> sensor_topic;
    sensor_topic.init(SENSOR_CMD, on_sensor_reading);
    mgr.create_subscription<SensorReading>(&sensor_topic);

    /* Register SetMotor service (request arrives via UART, reply goes via UART) */
    static SerialCommService<SetMotor_Request, SetMotor_Response> motor_svc;
    motor_svc.init(MOTOR_CMD, on_set_motor);
    mgr.create_service<SetMotor_Request, SetMotor_Response>(&motor_svc);

    if (mgr.start() != errCode::OK) {
        ESP_LOGE(TAG, "SerialCommManager start failed"); return;
    }

    /* ── Relay task ───────────────────────────────────────────────── */
    xTaskCreate(relay_task_fn, "relay", 4096, nullptr, 5, nullptr);

    ESP_LOGI(TAG, "Bridge running:");
    ESP_LOGI(TAG, "  UART (GPIO%d)  ──▶  receive SensorReading + SetMotor",
             uart_hw.rx_pin);
#ifdef USE_BROADCAST
    ESP_LOGI(TAG, "  ESP-NOW        ──▶  broadcast SensorReading to all peers");
#else
    ESP_LOGI(TAG, "  ESP-NOW        ──▶  unicast SensorReading to %02X:%02X:%02X:%02X:%02X:%02X",
             TARGET_MAC[0], TARGET_MAC[1], TARGET_MAC[2],
             TARGET_MAC[3], TARGET_MAC[4], TARGET_MAC[5]);
#endif

    /* app_main can return — relay_task and SerialComm tasks keep running */
}
