"""
generated_constants.py — Auto-generated by user_app/generate.py

Contains command IDs and IDL decorator metadata for all message types,
so the Python side can mirror the C++ constexpr values without re-parsing
the IDL files.

DO NOT EDIT MANUALLY — regenerate with:
    python3 user_app/generate.py --input user_app --output include/serial_comm/generated
"""

from ._types import DeliveryMode

# ---------------------------------------------------------------------------
# Command IDs
# ---------------------------------------------------------------------------

LEGACY_STATUS_ID        = 0x09   # LegacyStatus   (@deprecated)
ROBOT_VELOCITY_CMD_ID   = 0x10   # RobotVelocityCmd
ROBOT_TELEMETRY_ID      = 0x11   # RobotTelemetry

# ---------------------------------------------------------------------------
# Delivery modes  (mirrors DELIVERY_MODE constexpr in generated headers)
# ---------------------------------------------------------------------------

DELIVERY_MODE: dict[int, DeliveryMode] = {
    LEGACY_STATUS_ID:       DeliveryMode.BEST_EFFORT,
    ROBOT_VELOCITY_CMD_ID:  DeliveryMode.BEST_EFFORT,
    ROBOT_TELEMETRY_ID:     DeliveryMode.BEST_EFFORT,
}

# ---------------------------------------------------------------------------
# @max_rate_hz  (mirrors MAX_RATE_HZ constexpr)
# ---------------------------------------------------------------------------

MAX_RATE_HZ: dict[int, float] = {
    ROBOT_VELOCITY_CMD_ID: 33.0,
}

# ---------------------------------------------------------------------------
# @retain  (mirrors RETAIN constexpr)
# ---------------------------------------------------------------------------

RETAIN_COMMANDS: frozenset[int] = frozenset({
    ROBOT_TELEMETRY_ID,
})

# ---------------------------------------------------------------------------
# @timeout_ms  (mirrors TIMEOUT_MS constexpr; used by call_service)
# ---------------------------------------------------------------------------

# SetMotor does not have a fixed @id in the IDL example, so no entry here.
# Add:  TIMEOUT_MS[SET_MOTOR_ID] = 500  once you assign it an @id.
TIMEOUT_MS: dict[int, int] = {}

# ---------------------------------------------------------------------------
# @version  (mirrors SCHEMA_VERSION constexpr)
# ---------------------------------------------------------------------------

SCHEMA_VERSION: dict[int, int] = {
    ROBOT_TELEMETRY_ID: 1,
}

# ---------------------------------------------------------------------------
# @deprecated  (informational — types listed here should not be used in new code)
# ---------------------------------------------------------------------------

DEPRECATED_COMMANDS: frozenset[int] = frozenset({
    LEGACY_STATUS_ID,
})
