"""
generated_constants.py — Auto-generated by user_app/generate.py

Contains command IDs and IDL decorator metadata for all message types,
so the Python side can mirror the C++ constexpr values without re-parsing
the IDL files.

DO NOT EDIT MANUALLY — regenerate with:
    python3 user_app/generate.py --input user_app --output include/serial_comm/generated
"""

from ._types import DeliveryMode

# ---------------------------------------------------------------------------
# Command IDs
# ---------------------------------------------------------------------------

SERVO_STATUS_ID = 0x20
CUSTOM_DATA_ID = 0x13
SERVO_STATE_ID = 0x21
ROBOT_TELEMETRY_ID = 0x11
DISCOVERY_HELLO_ID = 0x12
LEGACY_STATUS_ID = 0x09   # (@deprecated)
ROBOT_VELOCITY_CMD_ID = 0x10
SET_MODE_ID = 0x14

# ---------------------------------------------------------------------------
# Delivery modes  (mirrors DELIVERY_MODE constexpr in generated headers)
# ---------------------------------------------------------------------------

DELIVERY_MODE: dict[int, DeliveryMode] = {
    SERVO_STATUS_ID: DeliveryMode.BEST_EFFORT,
    CUSTOM_DATA_ID: DeliveryMode.BEST_EFFORT,
    SERVO_STATE_ID: DeliveryMode.BEST_EFFORT,
    ROBOT_TELEMETRY_ID: DeliveryMode.BEST_EFFORT,
    DISCOVERY_HELLO_ID: DeliveryMode.BEST_EFFORT,
    LEGACY_STATUS_ID: DeliveryMode.BEST_EFFORT,
    ROBOT_VELOCITY_CMD_ID: DeliveryMode.BEST_EFFORT,
    SET_MODE_ID: DeliveryMode.RELIABLE,
}

# ---------------------------------------------------------------------------
# @max_rate_hz  (mirrors MAX_RATE_HZ constexpr)
# ---------------------------------------------------------------------------

MAX_RATE_HZ: dict[int, float] = {
    CUSTOM_DATA_ID: 5.0,
    ROBOT_VELOCITY_CMD_ID: 33.0,
}

# ---------------------------------------------------------------------------
# @retain  (mirrors RETAIN constexpr)
# ---------------------------------------------------------------------------

RETAIN_COMMANDS: frozenset[int] = frozenset({
    ROBOT_TELEMETRY_ID,
})

# ---------------------------------------------------------------------------
# @timeout_ms  (mirrors TIMEOUT_MS constexpr; used by call_service)
# ---------------------------------------------------------------------------

TIMEOUT_MS: dict[int, int] = {
    SET_MODE_ID: 1000,
}

# ---------------------------------------------------------------------------
# @version  (mirrors SCHEMA_VERSION constexpr)
# ---------------------------------------------------------------------------

SCHEMA_VERSION: dict[int, int] = {
    ROBOT_TELEMETRY_ID: 1,
}

# ---------------------------------------------------------------------------
# @deprecated  (informational)
# ---------------------------------------------------------------------------

DEPRECATED_COMMANDS: frozenset[int] = frozenset({
    LEGACY_STATUS_ID,
})
