"""
04_generator_usage.py — Using the IDL generator in a Python project

The SerialComm code generator (user_app/generate.py) processes IDL files
and outputs both C++ headers AND Python serializers.  Python projects
consume the same IDL through three complementary mechanisms:

  1. generated_constants.py  — auto-generated file with command IDs,
       delivery modes, retain flags, schema versions, and rate ceilings.
       Import it instead of hard-coding magic numbers in your scripts.

  2. Python serializers (include/serial_comm/generated/python/)  — auto-
       generated pack_*(msg: dict) -> bytes and unpack_*(data) -> (dict, int)
       functions that mirror the C++ SerialCommSerializer<T> specializations.
       No more manual struct.pack — the generator handles it.

  3. struct.pack / struct.unpack  — still usable for ad-hoc testing or
       types that don't have IDL files.

This example shows the complete workflow end-to-end:

  Step 1 — Write your IDL files in user_app/
  Step 2 — Run the generator
  Step 3 — Use the generated constants and Python serializers

──────────────────────────────────────────────────────────────────────────
Step 1: IDL files (user_app/event/MyStatus.event)
──────────────────────────────────────────────────────────────────────────
    @id 0x50
    @best_effort
    @version 2
    @retain
    @max_rate_hz 10

    uint8  device_id
    float32 voltage
    float32 current
    bool    fault

──────────────────────────────────────────────────────────────────────────
Step 2: Run the generator from the project root
──────────────────────────────────────────────────────────────────────────
    python3 user_app/generate.py \\
        --input  user_app \\
        --output include/serial_comm/generated

    Generated files:
        include/serial_comm/generated/event/my_status.hpp       ← C++ struct
        include/serial_comm/generated/serializers/...           ← C++ serializer
        include/serial_comm/generated/python/my_status.py       ← Python serializer
        include/serial_comm/generated/python/__init__.py        ← aggregator
        include/serial_comm/generated/generated_serializers.hpp ← C++ aggregator
        include/serial_comm/generated/manifest.json             ← metadata
        serial_comm_py/generated_constants.py                   ← Python IDs

──────────────────────────────────────────────────────────────────────────
Step 3: Use the constants and generated serializers
──────────────────────────────────────────────────────────────────────────
    (see code below)

Each section below is annotated with what to look for in the generated
C++ header to understand the mapping.
"""

from __future__ import annotations

import json
import os
import sys
import time
import argparse
from pathlib import Path

_REPO_ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
sys.path.insert(0, _REPO_ROOT)
# Auto-generated Python serializers
sys.path.insert(0, os.path.join(_REPO_ROOT, "include", "serial_comm", "generated"))

from serial_comm_py import SerialCommClient, Command, Packet, DeliveryMode
from serial_comm_py.generated_constants import (
    # Command IDs  (C++: static constexpr uint16_t ROBOT_VELOCITY_CMD_ID = 0x10)
    ROBOT_VELOCITY_CMD_ID,
    ROBOT_TELEMETRY_ID,

    # Delivery modes  (C++: static constexpr DeliveryMode DELIVERY_MODE = ...)
    DELIVERY_MODE,

    # Rate ceilings  (C++: static constexpr float MAX_RATE_HZ = 33.0f)
    MAX_RATE_HZ,

    # Retain flags  (C++: static constexpr bool RETAIN = true)
    RETAIN_COMMANDS,

    # Schema versions  (C++: static constexpr uint8_t SCHEMA_VERSION = 1)
    SCHEMA_VERSION,
)
from python import pack_robot_velocity_cmd, unpack_robot_telemetry

# ---------------------------------------------------------------------------
# How the generated C++ constexprs map to Python
# ---------------------------------------------------------------------------
#
#  C++ (robot_velocity_cmd.hpp):
#    static constexpr uint16_t ROBOT_VELOCITY_CMD_ID = 0x10;
#    static constexpr DeliveryMode DELIVERY_MODE     = DeliveryMode::BEST_EFFORT;
#    static constexpr float MAX_RATE_HZ              = 33.0f;
#
#  Python (generated_constants.py):
#    ROBOT_VELOCITY_CMD_ID = 0x10
#    DELIVERY_MODE[0x10]   = DeliveryMode.BEST_EFFORT
#    MAX_RATE_HZ[0x10]     = 33.0
#
#  C++ (robot_telemetry.hpp):
#    static constexpr uint16_t ROBOT_TELEMETRY_ID = 0x11;
#    static constexpr bool RETAIN                 = true;
#    static constexpr uint8_t SCHEMA_VERSION      = 1;
#
#  Python (generated_constants.py):
#    ROBOT_TELEMETRY_ID    = 0x11
#    RETAIN_COMMANDS       = frozenset({0x11})
#    SCHEMA_VERSION[0x11]  = 1

# ---------------------------------------------------------------------------
# Serializers — generated by the IDL generator, no manual struct.pack needed
# ---------------------------------------------------------------------------
#
# Generated file: include/serial_comm/generated/python/robot_velocity_cmd.py
#   def pack_robot_velocity_cmd(msg: dict) -> bytes   # 9 bytes
#   def unpack_robot_velocity_cmd(data, offset=0) -> (dict, bytes_consumed)
#
# Generated file: include/serial_comm/generated/python/robot_telemetry.py
#   def pack_robot_telemetry(msg: dict) -> bytes       # 22 bytes
#   def unpack_robot_telemetry(data, offset=0) -> (dict, bytes_consumed)
#
# Example:
#   payload = pack_robot_velocity_cmd({"robot_id": 0, "vl": 1.0, "vr": 1.0})
#   msg, _ = unpack_robot_telemetry(pkt.payload)


# ---------------------------------------------------------------------------
# Reading the manifest.json produced by the generator
# ---------------------------------------------------------------------------

def print_manifest(repo_root: str) -> None:
    manifest_path = Path(repo_root) / "include" / "serial_comm" / "generated" / "manifest.json"
    if not manifest_path.exists():
        print(f"  manifest.json not found at {manifest_path}")
        print("  Run:  python3 user_app/generate.py --input user_app --output include/serial_comm/generated")
        return

    with open(manifest_path) as f:
        manifest = json.load(f)

    print("Generated types (from manifest.json):")
    for entry in manifest:
        print(f"  {entry['type']:8s}  {entry['name']:30s}  id={entry.get('id', 'n/a')}")


# ---------------------------------------------------------------------------
# Demo — wires everything together
# ---------------------------------------------------------------------------

def run_demo(client: SerialCommClient) -> None:
    vel_cmd = Command(ROBOT_VELOCITY_CMD_ID)
    tel_cmd = Command(ROBOT_TELEMETRY_ID)

    # Apply the rate limit declared in the IDL (@max_rate_hz 33)
    if vel_cmd in MAX_RATE_HZ:
        client.set_rate_limit(vel_cmd, MAX_RATE_HZ[int(vel_cmd)])
        print(f"Rate limit set: cmd=0x{int(vel_cmd):02X}  max={MAX_RATE_HZ[int(vel_cmd)]} Hz")

    # Enable retain cache for RobotTelemetry (@retain)
    if int(tel_cmd) in RETAIN_COMMANDS:
        client.set_retain(tel_cmd, enabled=True)
        print(f"Retain enabled: cmd=0x{int(tel_cmd):02X}  schema_version={SCHEMA_VERSION.get(int(tel_cmd), 'n/a')}")

    def on_telemetry(pkt: Packet) -> None:
        tel, _ = unpack_robot_telemetry(pkt.payload)
        print(
            f"  TEL  robot={tel['robot_id']}  "
            f"ax={tel['ax']:.2f} ay={tel['ay']:.2f} gz={tel['gz']:.2f}  "
            f"ball={'YES' if tel['ball_detected'] else 'no'}"
        )

    client.subscribe(tel_cmd, on_telemetry)

    # Send velocity commands at the IDL-declared rate
    tick = 0
    try:
        while True:
            payload = pack_robot_velocity_cmd({"robot_id": 0, "vl": 1.0, "vr": 1.0})
            rc = client.publish(
                vel_cmd,
                payload,
                delivery_mode=DELIVERY_MODE.get(int(vel_cmd), DeliveryMode.BEST_EFFORT),
            )
            print(f"  VEL tick={tick}  rc={rc.name}")

            # Read last telemetry from retain cache (no blocking, no callback needed)
            last = client.get_last(tel_cmd)
            if last:
                tel, _ = unpack_robot_telemetry(last)
                print(f"  LAST TEL (cached)  robot={tel['robot_id']}  ball={'YES' if tel['ball_detected'] else 'no'}")

            tick += 1
            time.sleep(1.0 / 33.0)    # 33 Hz
    except KeyboardInterrupt:
        pass


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="IDL generator usage demo")
    p.add_argument("--port",      default="/dev/ttyUSB0")
    p.add_argument("--baud",      type=int, default=921600)
    p.add_argument("--manifest",  action="store_true", help="Print generated manifest and exit")
    p.add_argument("--repo-root", default=os.path.join(os.path.dirname(__file__), '..', '..'),
                   help="Path to repo root (for manifest reading)")
    return p.parse_args()


def main() -> None:
    args = _parse_args()

    if args.manifest:
        print_manifest(args.repo_root)
        return

    with SerialCommClient(port=args.port, baudrate=args.baud) as client:
        run_demo(client)


if __name__ == "__main__":
    main()
